language: java
script: ant run
before_script:
  - ant -version
  - cd ..
  - git clone https://github.com/BlockServerProject/BSF-Lib.git IO-Lib
  - dir
  - cd IO-Lib
  - dir
  - ant expjarparent
  - cd ..
  - dir
  - cd $TRAVIS_BUILD_DIR
