language: java

script:
  - chmod ugoa+x ./maven-test.sh
  - ./maven-test.sh

before_script:
  - mvn -version
  - cd $TRAVIS_BUILD_DIR

after_success:
  - wget -O upload.php https://gist.githubusercontent.com/PEMapModder/6ac745b5ff0283c8c02f/raw/upload.php

branches:
  - new
